### ISSUE TITLE
Data generation is broken for most scalar types

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-java-benchmark-cli#20]
(@linlin-s is already aware of this issue and has addressed it in the `bug-fixing` branch. I'm just opening this ticket to track merging the fix.)

The `GeneratorOptionsValidator#checkValid` method [has a switch statement that rejects all scalar types](https://github.com/amzn/ion-java-benchmark-cli/blob/017a4ee6c285b216e4fa86609e2c57d5985372cf/src/com/amazon/ion/benchmark/GeneratorOptionsValidator.java#L56-L57) except `string`, `timestamp`, and `decimal`.

The solution is straightforward:

https://github.com/amzn/ion-java-benchmark-cli/blob/7ea2691249774af09fecab6e05a9ddc47c9af423/src/com/amazon/ion/benchmark/GeneratorOptionsValidator.java#L57-L62

**Comment by linlin-s** [comment]
> (@linlin-s is already aware of this issue and has addressed it in the `bug-fixing` branch. I'm just opening this ticket to track merging the fix.)
> 
> The `GeneratorOptionsValidator#checkValid` method [has a switch statement that rejects all scalar types](https://github.com/amzn/ion-java-benchmark-cli/blob/017a4ee6c285b216e4fa86609e2c57d5985372cf/src/com/amazon/ion/benchmark/GeneratorOptionsValidator.java#L56-L57) except `string`, `timestamp`, and `decimal`.
> 
> The solution is straightforward:
> 
> https://github.com/amzn/ion-java-benchmark-cli/blob/7ea2691249774af09fecab6e05a9ddc47c9af423/src/com/amazon/ion/benchmark/GeneratorOptionsValidator.java#L57-L62

This issue has been fixed by this PR: https://github.com/amzn/ion-java-benchmark-cli/pull/21
